[tool.black]
target-version = ['py38']

[tool.isort]
profile = "black"
known_django = "django"
known_first_party = ['django-rules']
sections = ['FUTURE', 'STDLIB', 'DJANGO', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
skip=['migrations', '.git', '__pycache__', 'venv']
